### ISSUE TITLE
HexiWear App Mode characteristic notifications do not work on iOS

### ISSUE THREAD

**Issue by mikaelkindborg** [evothings/cordova-ble#112]
Subscribing for notifications for characteristic 0x2041 on the HexiWear does not work on iOS. Other characteristics work.

Error message from the iOS plugin: "enableNotification error: The attribute could not be found."

Googling for "The attribute could not be found" gives some results that might be useful.

HexiWear BLE documentation page:

https://github.com/MikroElektronika/HEXIWEAR/blob/master/documentation/HEXIWEAR%20Bluetooth%20Specifications.pdf

**Comment by mikaelkindborg** [comment]
Also see issue: https://github.com/evothings/evothings-examples/issues/205

**Comment by ghost** [comment]
Turns out this is by design, notifications are not available for all characteristics. Closing issue.
