### ISSUE TITLE
test.html cordova ios does not read services?

### ISSUE THREAD

**Issue by mrbbp** [evothings/cordova-ble#131]
I'm sorry for this simple question...
i've compiled an app with xcode on ipad
it startscan and found a device, the page said
"LOG:  testConnectClose(0) device: 5BB1CA9F-xxxx-...." and nothing more.
Doesn't it suppose to list the services available on the device found ?

regards

é.

**Comment by mrbbp** [comment]
ok i've found
i've modified the script line 189, i've changed the signe < to > and have a services reading
`if (counter > 10)
	{
		evothings.ble.close(info.deviceHandle);
	}`

**Comment by ghost** [comment]
@mrbbp Great to hear you fixed the problem.  If this is related to any issue with ble.js let me know so I can fix.
