### ISSUE TITLE
Problem with Android build

### ISSUE THREAD

**Issue by ghost** [evothings/cordova-ble#28]
### Problem

Build problem reported on Twitter by @nrocy
https://twitter.com/nrocy/status/449169997089497088

Log: http://norc.homeip.net/~nroc/x/DEZT5.png
### Steps to attempt to recreate

Folder structure used:

```
code
    cordova-ble
    micketest
```

Cloned repo evothings/cordova-ble from GitHub into the folder structure as shown above.

Created Cordova project and build with the following commands (on OS X):

```
cordova create micketest com.kindborg.micketest MickeTest
cd MickeTest
cordova platform add android
cordova plugin add ../cordova-ble/
cordova build
```

This built a project with the plugin installed (did not recreate the problem).

@nrocy Can you fill in with more detail?

**Comment by J0nnie** [comment]
Was this fixed or what is the status. I have tried the steps 
cordova platform add android
cordova plugin add https://github.com/evothings/cordova-ble
cordova run
with no luck so far. I also get the error, Link of class 'Lcom/evothings/BLE;' failed

**Comment by fredrikeldh** [comment]
I just ran this in an empty directory:
```
cordova create .
cordova platform add android
cordova plugin add https://github.com/evothings/cordova-ble
cordova run
```
No problems. In particular, I did not get your Link error.

**Comment by J0nnie** [comment]
I get the following errors

Caused by: java.lang.NoClassDefFoundError: com/evothings/BLE
......
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.evothings.BLE" on path: /data/app/com.ble.test-1.apk
.....
Error adding plugin com.evothings.BLE

**Comment by fredrikeldh** [comment]
I should add that I am using Cordova 3.6.3. cordova-ble is not compatible with Cordova 4.

**Comment by J0nnie** [comment]
I have Android 3.7.1. Should that be a problem?

**Comment by fredrikeldh** [comment]
I'm sorry, *Android* 3.7.1? That's not a thing.

You must mean Cordova 3.7.1. Haven't tried it; I think it's not officially released. It might work, but since we can't find any other problem sources, I suggest you test using 3.6.3-0.2.13 instead.

**Comment by J0nnie** [comment]
It was Cordova 4.3.0 and I have now downgradet to 3.6.3-0.2.13, but I still experience the samt problem as soon as I run e.g. evothings.ble.reset() or anything else with evothings. If I just create an new project and and add the plugin then there is no errors but as soon as evothings is referenced from the code the error is there. I have used the project that nrocy has made to test https://github.com/nrocy/bletest-example

**Comment by J0nnie** [comment]
Problem solved. The problem was a combination of two things. Cordova 4.x and then afterwards a not updated version of Android. The phone could find the beacons from the settings but apparently the plugin could not. Thanks for your help with the Cordova version!

**Comment by divineprog** [comment]
Thanks a lot for the update! Glad you could find a solution :)
