### ISSUE TITLE
connect() not returning

### ISSUE THREAD

**Issue by empinator** [evothings/cordova-ble#29]
Hey,

similar to the evothings examples, I have a very simple project. 

My problem is that in most cases connect() is not returning, although sometimes it does return (rarely) but it takes at least 5 min. 

All I want do at this point is connecting and reading the services. Consuming the services with a laptop worked so far.

Phone: Galaxy S4 Mini with CyanogenMod 11-20140315-nightly, Android 4.4.2
Peripheral: Raspberry PI with Bluetooth-Dongle

Any help or pointers for pointers would be highly appreciated.
(I hope you're not blaming CyanogenMod ;-) )

Code:
```JavaScript
	$scope.stopBleScan();
	console.log('connect(' + address + ')', new Date());
	ble.connect(address, function (r) {
		console.log('connect ' + r.deviceHandle + ' state ' + r.state, new Date());
		if (r.state == 2) {
			console.log('connected, requesting services...');
			$scope.getServices(r.deviceHandle);
		}
	}, function (errorCode) {
		console.log('connect error: ' + errorCode);
	});
```

**Comment by mikaelkindborg** [comment]
What is the status of this issue? Is the conclusion that this is a problem specific to certain Android devices/versions?

Can this issue be closed?

**Comment by empinator** [comment]
I have changed plans on my project and went a different, technical, direction. So this issue is no longer relevant to me. 
Unfortunately I can't say if it still exists, but I guess not, since rcugut pointed out that it's working for him. 
I am very sorry for not following up.

**Comment by mikaelkindborg** [comment]
@empinator Thanks a lot for the update!
