### ISSUE TITLE
How to register for Notification / Indication 

### ISSUE THREAD

**Issue by etx** [evothings/cordova-ble#30]
This plugin looks great so far! 

Is their any available example of how to register to recieve notifications or indications? I see the notes in the jsdoc comments for enableNotification about having to "write a special value to a separate configuration characteristic". I'm guessing that something like writing the BluetoothGattDescriptor.ENABLE_INDICATION_VALUE on android, But I'm not sure how to pull that off on the Javascript side.

**Comment by thegecko** [comment]
This is only required on android devices AFAIK and should be encapsulated in the native android code to keep the API consistent across iOS and Android devices.

**Comment by jrobeson** [comment]
is this bug report still valid?

**Comment by jrobeson** [comment]
yes, it sure is! :(

**Comment by jrobeson** [comment]
this is the correct url for that now: https://github.com/CANBus-Triple/CANBus-Triple-App/blob/master/www/js/app/services/BluetoothService.js

**Comment by jrobeson** [comment]
@thegecko: that's exactly how https://github.com/sandeepmistry/noble does too

**Comment by thegecko** [comment]
@jrobeson, I haven't looked into this issue recently, but although other libraries may require this bit to be explicitly written, I seem to remember the iOS implementation of evothings doesn't need it. If that's the case, you should strive to make the interface for evothings the same across all implementations.

**Comment by jrobeson** [comment]
yep, at least android does. no idea about windows phone

**Comment by mikaelkindborg** [comment]
Android implementation is now updated to automatically write the notification config descriptor when turning notifications on or off.

Indication is not supported at the moment. Should indications be needed, one idea is to implement a new function for this in the BLE JavaScript API (and add the corresponding native implementation). If this is done, research how indications work on iOS and make a compatible solution.

Last commit for the new implementation is https://github.com/evothings/cordova-ble/commit/549ce740c44242e9d230a38a0d810736c86d6839

**Comment by CCommander** [comment]
I am using the function app.device.enableNotification in my Evothings app. In the Evothings viewer App on iOS this works perfectly. In the Evothings viewer app on Android a lot of notifications are missed and my app does not work as desired. 

Is this a known issue?

**Comment by mikaelkindborg** [comment]
@CCommander Hi, notifications are expected to work on Android, so I would not say this is a known issue. Would you mind open a new issue for this problem?
