### ISSUE TITLE
i found the device,but the uuid is incorrect?

### ISSUE THREAD

**Issue by gaecom** [evothings/cordova-ble#35]
this is correct data
{ranged: [{ uuid: "74278BDA-B645-4520-8F0C-720EAF059935", major: 10, minor: 10, rssi: -60, power: -59 }]}

and your lib cordova-ble on iphone5s 7.01 got this data
{"scanRecord":"","rssi":-46,"name":"HMSensor","address":"097B6444-8691-5631-20DB-E56886D373CD"}

**Comment by fredrikeldh** [comment]
This is not an iBeacon plugin; that would be https://github.com/evothings/cordova-plugin-ibeacon. Closing issue.
