### ISSUE TITLE
D/BluetoothAdapter( 7682): startLeScan(): null

### ISSUE THREAD

**Issue by mobilars** [evothings/cordova-ble#38]
I maybe over-eagerly reset the BLE stack on the Android device, and sometimes it doesn't start up properly. This means that I start the scanning without there being a valid BLE device. But I don't seem to get a proper feedback that BLE isn't running. 

Should the error callback of easyble.startScan be called when the above happens? I can't see that happening. I'm using slightly old code, so I apologize if this has been updated since I updated.

**Comment by renlinx007** [comment]
startLeScan() :null is a debug message from BluetoothAdapter if UUID filter not given.
startLeScan(callback) actually calling startLeScan(null,callback).
in startLeScan(null,callback) method
they are just logging Log.d("BluetoothAdapter","startLeScan(): "+null);
This has nothing to do with callback 
My Callback is not calling until this time I was just searching through and found this page

**Comment by UgurYasarKazdal** [comment]
I have this startLeScan(): null log message. and not have any results from scan.

**Comment by CortoMaltese83** [comment]
Hi sideffect0 so which could be a workaround? I have the same problem both device with Android 6.0, one device does scan propertly and the other not

**Comment by arvindpdmn** [comment]
Just started using evothings. Ran the Arduino LED On/Off BLE example and got error: Android function startLeScan failed. Anything missing on my device or installation?

**Comment by sideffect0** [comment]
@arvindpdmn checked bluetooth permissions ?
@CortoMaltese83 if its android 6.0 check docs on how to request permissions

**Comment by mikaelkindborg** [comment]
Is this problem still an issue? The plugin has been updated several times sine last activity on this issue, closing it for now. Let me know if to reopen.
