### ISSUE TITLE
ios background mode

### ISSUE THREAD

**Issue by sce9sc** [evothings/cordova-ble#39]
I've used this plugin with great success. I recently bought a lightblue bean (Arduino with ble) and worked great with this plugin. The only problem that I am facing is that there is no background service and thus when the app goes in the background it does not wake up when there is a change in a characteristic . I would be nice is someone could implement background mode in ios (and android) for bluetooth.

**Comment by mikaelkindborg** [comment]
Support for background scanning available in this branch: https://github.com/mikaelkindborg/cordova-ble/tree/background

Will be merged to master branch.
