### ISSUE TITLE
Android Unsigned Int Array

### ISSUE THREAD

**Issue by AlexMcDuffMiller** [evothings/cordova-ble#50]
I'm running into an issue with unsigned vs signed bytes.  I'm sending data over BLE by passing an unsigned int array, but when the code runs on Android it converts it to a signed int.  When that happens, the data that I'm trying to send never actually gets sent because the values get changed.  Has anyone else experienced this?

**Comment by fredrikeldh** [comment]
I've never experienced it. I've looked at the relevant plugin code and don't see how the plugin could possible cause it.

To investigate further, we would need more information. The source code of a program that exhibits the problem would be useful.
