### ISSUE TITLE
RSSI Polling only works once.

### ISSUE THREAD

**Issue by dwilliams** [evothings/cordova-ble#52]
After polling the RSSI value for a BLE device using the evothings.ble.rssi function, any following attempts to poll the RSSI for the device fail with the following error message: "Previous call to rssi() not yet completed!"

It appears the mRssiContext is not being reset to null after the callbackContext (which is assigned to mRssiContext) completes.

**Comment by fredrikeldh** [comment]
Works fine on iOS.

The Android code in question does seem buggy. Testing a fix... it worked.
