### ISSUE TITLE
Using this module with Angular Cordova

### ISSUE THREAD

**Issue by matdev** [evothings/cordova-ble#60]
I'd like to use the cordova-ble module with ionic using ngCordova

What is the procedure to make the module ngCordova compatible ?

**Comment by fredrikeldh** [comment]
> What is the procedure to make the module ngCordova compatible?
I don't know; have never used ngCordova. I suppose you can ask them to add it.

However, they have already added [another BLE module](https://github.com/driftyco/ng-cordova/blob/master/src/plugins/ble.js), based on the plugin cordova-plugin-ble-central. You could try that.
