### ISSUE TITLE
startScan returns the same device over and over

### ISSUE THREAD

**Issue by u84six** [evothings/cordova-ble#66]
Is this the way it works? In the comments it says that it calls the callback when a new device is detected. When I run startScan, it keeps returning the same device until I call stopScan.

**Comment by fredrikeldh** [comment]
You are correct; the comment is misleading.

The scanCallback is called each time an advertisement is recieved. Most BLE devices send advertisements roughly once per second.

**Comment by u84six** [comment]
Thanks for the response!
