### ISSUE TITLE
Different address for the same device across Android and IOS

### ISSUE THREAD

**Issue by dested** [evothings/cordova-ble#73]
When I scan for devices on android I get a shorter address (eg. AB:CD:EF:12:34) vs IOS which gives me a longer uuid looking address. My goal is to store the address in a database and auto connect to it, regardless of the originating operating system. To do this I need to be able to convert from one to the other to determine that the device I scanned for is the original device I connected to. Thoughts?

**Comment by fredrikeldh** [comment]
You may be able to use "advertisementData", a member of the DeviceInfo object you get in startScan()'s callback.

You'll need to use the [easyble](https://github.com/evothings/evothings-examples/blob/master/resources/libs/evothings/easyble/easyble.js) library to get this field on Android.

Not all BLE devices advertise unique data, but if you have control of the device firmware, you should be able to make it happen.
