### ISSUE TITLE
Version handling

### ISSUE THREAD

**Issue by divineprog** [evothings/cordova-ble#75]
Plugin version is still 0.0.1. Suggest we do releases in GitHub and update the version number so that it is possible for people to track plugin versions. What about adding the plugin to npm, as with the core Cordova plugins?

**Comment by fredrikeldh** [comment]
Yeah, I've been meaning to do that. Maybe bump it to 1.0.0, then adding it to npm?

**Comment by divineprog** [comment]
Sweet :)

**Comment by divineprog** [comment]
Version is now set to 1.0.0 and plugin available on npm as cordova-ble. Closing this issue
