### ISSUE TITLE
Add functions to check if Bluetooth is off and to turn it on

### ISSUE THREAD

**Issue by mikaelkindborg** [evothings/cordova-ble#86]
See question asked in this forum thread: http://evothings.com/forum/viewtopic.php?f=8&t=1886&p=4640

**Comment by fredrikeldh** [comment]
At least Android has this already:
https://github.com/evothings/cordova-ble/blob/55456d4db2a54a57fed64e231f2f993699ca4e1c/src/android/BLE.java#L123

But it looks like iOS doesn't:
https://github.com/evothings/cordova-ble/blob/55456d4db2a54a57fed64e231f2f993699ca4e1c/src/ios/EVOBLE.m#L1457

**Comment by mikaelkindborg** [comment]
On iOS, if Bluetooth is turned off, a popup menu is displayed when the app starts. The menu has an option for opening the Settings app, where Bluetooth can be turned on. This is the behaviour on iOS. Closing this issue.
